/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_rogerdemo_JNI_JniUtils */

#ifndef _Included_com_example_rogerdemo_JNI_JniUtils
#define _Included_com_example_rogerdemo_JNI_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_rogerdemo_JNI_JniUtils
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_rogerdemo_JNI_JniUtils_getStringFromNDK
  (JNIEnv *, jclass);

/*
 * Class:     com_example_rogerdemo_JNI_JniUtils
 * Method:    getDate
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_rogerdemo_JNI_JniUtils_getDate
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
